services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  consumer:
    build: .
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - .:/app
    command: ["python", "consumer.py"]

  producer:
    build: .
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - .:/app
    command: ["/wait-for-it.sh", "rabbitmq", "5672", "30", "--", "python", "producer.py"]
